name: Trigger auto deployment for recruiting-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '"/Dockerfile_recruiting"/**'
    - '.github/workflows/recruiting-container-AutoDeployTrigger-f721b4de-467c-40eb-aa15-afb19d4ebc1f.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RECRUITINGCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}"/Dockerfile_recruiting" 
          registryUrl: lan2023cr.azurecr.io
          registryUsername: ${{ secrets.RECRUITINGCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RECRUITINGCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: recruiting-container
          resourceGroup: May2023Batch
          imageToBuild: lan2023cr.azurecr.io/recruiting-container:${{ github.sha }}
          dockerfilePath: Dockerfile

     

